### ISSUE TITLE
Lake scenario

### ISSUE THREAD

**Issue by melissamillares** [MCV-Univalle/MementoVR#73]
Create a scenario with a lake (separate the garden scenario into two scenarios).

**Comment by melissamillares** [comment]
New garden scenario:
![garden](https://user-images.githubusercontent.com/26610889/77834794-468b2f00-7115-11ea-958d-88a0ccc8079d.JPG)
Lake scenario:
![lake](https://user-images.githubusercontent.com/26610889/77834796-47bc5c00-7115-11ea-8ec3-e5e11362058f.JPG)

**Comment by jpcv222** [comment]
Issue checked. 
Note: Some of the buttons in the upper left corner are not very visible on the screen.
![lakescenario.png](https://images.zenhubusercontent.com/5d1d50c49c916c09a936e985/433d7190-886c-4c1b-aa34-69d9d49bb6ad)
