### ISSUE TITLE
Tutorial navigation

### ISSUE THREAD

**Issue by melissamillares** [MCV-Univalle/MementoVR#76]
@jpcv222 commented on [Thu Mar 05 2020](https://github.com/MCV-Univalle/Memento/issues/141)

The tutorial should have the option to close.
The tutorial must allow navigation with "Anterior" and "Siguiente" buttons

**Comment by melissamillares** [comment]
![1](https://user-images.githubusercontent.com/26610889/77604106-b2845200-6edf-11ea-8e3c-13543fff5647.png)
![2](https://user-images.githubusercontent.com/26610889/77604103-b1ebbb80-6edf-11ea-826c-1a07c5d77dd7.png)
![3](https://user-images.githubusercontent.com/26610889/77604100-b021f800-6edf-11ea-881a-1e1b0fd2a3d9.png)

**Comment by andresow** [comment]
Revisado
