### ISSUE TITLE
Show message when one object is deleted from the scenario

### ISSUE THREAD

**Issue by melissamillares** [MCV-Univalle/MementoVR#85]
Show a message to the user that specifies when one object is deleted from the scenario

**Comment by melissamillares** [comment]
![Sin título](https://user-images.githubusercontent.com/26610889/83100041-89fe0d00-a074-11ea-95e1-2065f74648a7.png)

**Comment by jpcv222** [comment]
Checked.
I recommend using a dark color for the message in this scenario, maybe for the panel.
