### ISSUE TITLE
Water, at the lake scenario, disappears

### ISSUE THREAD

**Issue by melissamillares** [MCV-Univalle/MementoVR#90]
Water, at the lake scenario, disappears when the camera view is changed

**Comment by melissamillares** [comment]
View of the lake in browser

![lago2 - copia](https://user-images.githubusercontent.com/26610889/83161096-98c4de00-a0cd-11ea-92ff-e2f49f307812.png)

![lago1](https://user-images.githubusercontent.com/26610889/83160719-281dc180-a0cd-11ea-8d4c-66e0724a4eaa.png)

**Comment by jpcv222** [comment]
Checked,
Note: Ducks are standing in the lake.
